name: CI

on:
  workflow_dispatch:
  release:
    types: [ published ]
  # push:
  #   # branches: [ main ]
  #   # Pattern matched against refs/tags
  #   tags:
  #   - "*" # Push events to every tag not containing /
  # workflow_run:
  #   workflows: [ "Bump version" ]
  #   types: [ completed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Install dependencies
        run: sudo apt install -y python3 python3-jwt python3-requests

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Mainnet deploying
        run: deploy/dispatch_workflow.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET: "mainnet"
          TARGET_REPO: "krogla/test-infra"
          TARGET_WORKFLOW: "deploy.yaml"
